name: run docker compose

on:
  pull_request:
    branches:
      - main

jobs:
  docker-compose:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: run test
        run: docker compose run test
