name: test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: use checkout
        uses: actions/checkout@v2

      - name: use python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: install depends
        run: |
          pip install -r requirements.txt
          pip install pytest

      - run: pytest
